<?php
  
/**
 * Implements hook_theme().
 */
function vscc_ldap_theme ($existing, $type, $theme, $path) {
  return [
    'vscc_ldap_page' =>
    array(
      'variables' => array(
        'markup' => null,
        'results' => null,
      ), 
      'template' => 'page--Directory'
    )
  ];
}

/**
 * Queries LDAP for given search parameters
 */
function people_finder_results($last_name,$dept,$job_title) {
  
  // sanitize input
	$searchname = (isset($last_name) && $last_name != '') ? filter_var($last_name, FILTER_SANITIZE_STRING)  : '';
	$searchdept = (isset($dept) && $dept != '') ? filter_var($dept, FILTER_SANITIZE_STRING)  : '';
	$searchtitle = (isset($job_title) && $job_title != '') ? filter_var($job_title, FILTER_SANITIZE_STRING)  : '';
  
  // connect to the vscc_web database
  \Drupal\Core\Database\Database::setActiveConnection('webdb');
  $connection = \Drupal\Core\Database\Database::getConnection();
  
  // query the people records from the database
  $query = $connection->select('people', 't')->fields('t', array('name','title','department','office','phone','email','photo'));
  
  // query by department
	if(isset($dept) && !empty($dept)) {
  	if (strtoupper($dept) == 'HEALTH SCIENCES') {
    	$query->condition('department', '%' . $dept, 'LIKE');
  	} else {
    	$query->condition('department', '%' . $dept . '%', 'LIKE');
    }
	} 
	
	// query by last name
	if(isset($last_name) && !empty($last_name)) {
		$query->condition('name', $last_name . '%', 'LIKE');
	} 
	
	// query by job title
	if(isset($job_title) && !empty($job_title)) {
    $db_or = db_or();
  	if (strtoupper($job_title) == 'EMT') {
    	$db_or->condition('title', '%EMT%' , 'LIKE');
    	$db_or->condition('title', '%EMS%' , 'LIKE');
  	} elseif (strtoupper($job_title) == 'PERFORMING ARTS') {
    	$db_or->condition('title', '%Music%' , 'LIKE');
    	$db_or->condition('title', '%Theater%' , 'LIKE');
  	} elseif (strtoupper($job_title) == 'ENGLISH') {
    	$db_or->condition('title', '%English%' , 'LIKE');
    	$db_or->condition('title', '%Language%' , 'LIKE');
  	} elseif (strtoupper($job_title) == 'FOREIGN LANGUAGE') {
    	$db_or->condition('title', '%Foreign%' , 'LIKE');
    	$db_or->condition('title', '%Spanish%' , 'LIKE');
  	} elseif (strtoupper($job_title) == 'RADIOLOGY') {
    	$db_or->condition('title', '%Radiology%' , 'LIKE');
    	$db_or->condition('title', '%Radiologic%' , 'LIKE');
  	} elseif (strtoupper($job_title) == 'VETERINARY') {
    	$db_or->condition('title', '%Vet Tech%' , 'LIKE');
    	$db_or->condition('title', '%Veterinary%' , 'LIKE');
  	} else {
  		$db_or->condition('title', '%' . $job_title . '%' , 'LIKE');
    }
    $query->condition($db_or);
	} 

  // sort by name
  $query->orderBy('name', 'ASC');
    
  // loop through results
  $resultsArr = array();
  $result = $query->execute();
  while($record = $result->fetchAssoc()) 
  {
    // process values
    $photoURL = 'https://web.volstate.edu/_files/images/employees/';
    $imageURL = $photoURL . $record['photo'] . '.jpg';
    if (url_file_exists($imageURL))
       $dirImg = $imageURL;
    else
       $dirImg = $photoURL . '/noimg.jpg'; // display no image (gray avatar)

    if (isset($record['department']) && $record['department'] !== '') {
      $department = $record['department'];
    }
    else {
      $department = '';
    }
    
    if (isset($record['office']) && $record['office'] !== '') {
      $office = $record['office'];
    }
    else {
      $office = '';
    }
    
    if (isset($record['phone']) && $record['phone'] !== '') {
      $phone = $record['phone'];
    }
    else {
      $phone = '';
    }
    
    // store values in an array
    $resultsArr[] = array(
  		'photo' => $dirImg,
  		'name' => $record['name'],
  		'email' => $record['email'],
  		'title' => $record['title'],
  		'department' => $department,
  		'office' => $office,
  		'phone' => $phone

  	);
  } // end while
  
  // set connection back to main Drupal database
  \Drupal\Core\Database\Database::setActiveConnection();

  // return the array
	return $resultsArr;

}


/**
 * Check if external URL exists
 */
function url_file_exists($url) {
  $url = str_replace(' ', '%20', $url);
  $ch = curl_init($url);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); 
  curl_setopt($ch, CURLOPT_NOBODY, true);
  curl_exec($ch);
  $httpcode = curl_getinfo($ch, CURLINFO_HTTP_CODE);  
  curl_close($ch);
  if($httpcode>=200 && $httpcode<300){  return true; } else { return false; } 
}