<?php
  
/**
	* search LDAP and display results
	*
	* @param string $last_name
	* @param string $dept
	*
	* @return $results
	*/
	
function people_finder_results($last_name,$dept,$job_title) {
  
  // sanitize input
	$searchname = (isset($last_name) && $last_name != '') ? filter_var($last_name, FILTER_SANITIZE_STRING)  : '';
	$searchdept = (isset($dept) && $dept != '') ? filter_var($dept, FILTER_SANITIZE_STRING)  : '';
	$searchtitle = (isset($job_title) && $job_title != '') ? filter_var($job_title, FILTER_SANITIZE_STRING)  : '';
  
  /* connect to the database */
  \Drupal\Core\Database\Database::setActiveConnection('webdb');
  $connection = \Drupal\Core\Database\Database::getConnection();
  
  /* query the people records from the database */
  $query = $connection->select('people', 't')->fields('t', array('name','title','department','office','phone','email','photo'));
  
  // search by department
	if(isset($dept) && !empty($dept)) {
  	$query->condition('department', '%' . $dept . '%', 'LIKE');
	} 
	
	// search by last name
	if(isset($last_name) && !empty($last_name)) {
		$query->condition('name', $last_name . '%', 'LIKE');
	} 
	
	// search by job title
	if(isset($job_title) && !empty($job_title)) {
    $db_or = db_or();
  	if (strtoupper($job_title) == 'EMT') {
    	$db_or->condition('title', '%EMT%' , 'LIKE');
    	$db_or->condition('title', '%EMS%' , 'LIKE');
  	} elseif (strtoupper($job_title) == 'PERFORMING ARTS') {
    	$db_or->condition('title', '%Music%' , 'LIKE');
    	$db_or->condition('title', '%Theater%' , 'LIKE');
  	} elseif (strtoupper($job_title) == 'ENGLISH') {
    	$db_or->condition('title', '%English%' , 'LIKE');
    	$db_or->condition('title', '%Language%' , 'LIKE');
  	} elseif (strtoupper($job_title) == 'FOREIGN LANGUAGE') {
    	$db_or->condition('title', '%Foreign%' , 'LIKE');
    	$db_or->condition('title', '%Spanish%' , 'LIKE');
  	} else {
  		$db_or->condition('title', '%' . $job_title . '%' , 'LIKE');
    }
    $query->condition($db_or);
	} 

  // sort by name
  $query->orderBy('name', 'ASC');
    
  // output the results
  $results = '<div class="pplFinder">';
    
  $result = $query->execute();
  while($record = $result->fetchAssoc()) 
  { 
    
    // check if photo file exists
    $photoURL = 'http://XXXXX/_files/images/employees/';
    if (url_file_exists($photoURL . $record['photo'] . '.jpg'))
       $dirImg = $photoURL . $record['photo'] . '.jpg';
    else
       $dirImg = $photoURL . '/noimg.jpg'; // display no image (gray avatar)
       
    $results = $results . '<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 person">';    // person
          
      // image
      $results = $results . '<div class="col-xs-4 col-sm-4 col-md-4">';
        $results = $results . '<img src="'.$dirImg.'" alt="'. $record['name'] .'" />';
        $results = $results . '</div>';
        
        // contact info
        $results = $results . '<div class="col-xs-8 col-sm-8 col-md-8">';
        $results = $results . '<h2><a href="mailto:' . $record['email'] . '" title="' . $record['name'] . '">' . $record['name'] . '</a></h2>';
        $results = $results . '<div class="pfTitle">' . $record['title'] . '</div>';
        
        $results = $results . '<div class="pfContact">';
        if (isset($record['department']) && $record['department'] !== '') {
          $results = $results . '<div class="pfDept">' . $record['department'] . '</div>';
        }
        if (isset($record['office']) && $record['office'] !== '') {
        $results = $results . $record['office'] . '<br>'; 
        }
        if (isset($record['phone']) && $record['phone'] !== '') {
          $results = $results . $record['phone'];
        }
      $results = $results . '</div>'; // pfContact
      $results = $results . '</div>'; // column
    $results = $results . '</div>';   // person
        
  } // loop
    
  $results = $results . '</div>';     // pplFinder
  
  // set connection back to main Drupal database
  \Drupal\Core\Database\Database::setActiveConnection();

	return $results;   // output results to the page

}

// check if url file exists
function url_file_exists($url) {
  $headers=get_headers($url);
  return stripos($headers[0],"200 OK")?true:false;
}